name: go
on:
  push:
    branches:
    - '**'
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}    

jobs:
  check_docs_only:
    name: check_docs_only
    runs-on: ubuntu-18.04
    outputs:
      skip: ${{ steps.check_docs_only.outputs.skip }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: check_docs_only
        # Since PR's are squashed prior to merging to the branch checked out (default branch),
        # HEAD^ will resolve to the previous point in history.
        run: |
          REF="HEAD^"
          [[ -z "${{ github.base_ref }}" ]] || REF=$(git show-ref ${{ github.base_ref }} | head -1 | cut -d' ' -f2)
          echo "::set-output name=skip::$(.github/workflows/check-docs-only.sh $REF)"



  unit:
    name: unit
    runs-on: ubuntu-18.04
    needs: check_docs_only
    if: needs.check_docs_only.outputs.skip != 'true'
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: make test-unit
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out

  # Job matrix for image builds. Only pushes if a tag with prefix "v" is present.
  images:
    name: images
    needs: check_docs_only
    # Run this job on a tag like 'vX.Y.Z' or on a branch or pull request with code changes.
    if: startsWith(github.ref, 'refs/tags/v') || ( needs.check_docs_only.outputs.skip != 'true' && !startsWith(github.ref, 'refs/tags/') )
    runs-on: ubuntu-18.04
    environment: deploy
    strategy:
      matrix:
        id: ["operator-sdk", "helm-operator", "scorecard-test", "ansible-operator", "ansible-operator-2.11-preview"]
    steps:

    - name: set up qemu
      uses: docker/setup-qemu-action@v1

    - name: set up buildx
      uses: docker/setup-buildx-action@v1

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: |
        gcloud info
        gcloud auth configure-docker europe-west1-docker.pkg.dev

  
    # Check out repo before tag step for script.
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: create tags
      id: tags
      run: |
        IMG=$(cat Makefile |grep "BUILD_IMAGE_REPO = "|cut -d '=' -f2|tr -d ' ')/${{ matrix.id }}
        echo ::set-output name=tags::$(.github/workflows/get_image_tags.sh "$IMG" "v")

    - name: build and push
      uses: docker/build-push-action@v2
      with:
        file: ./images/${{ matrix.id }}/Dockerfile
        context: .
        platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
        # Push on tag, or master or latest branch push.
        push: ${{ (github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/latest')) }}
        tags: ${{ steps.tags.outputs.tags }}

